// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwQrvbPwUqffI7Y5k473OkNuSehur-uFc',
    appId: '1:39180378564:web:d92cdbd5d652fca414c491',
    messagingSenderId: '39180378564',
    projectId: 'cocinando-ando-94999',
    authDomain: 'cocinando-ando-94999.firebaseapp.com',
    storageBucket: 'cocinando-ando-94999.firebasestorage.app',
    measurementId: 'G-B5EKCNX1XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzN9Xi7fIH0yjwsLpmYGOBZuH1YhX0tos',
    appId: '1:39180378564:android:a2d242b90bc7bacd14c491',
    messagingSenderId: '39180378564',
    projectId: 'cocinando-ando-94999',
    storageBucket: 'cocinando-ando-94999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEa3WWOLyYASlIRswHKH1h8Ipw86LqBK0',
    appId: '1:39180378564:ios:e958eac259dbac4314c491',
    messagingSenderId: '39180378564',
    projectId: 'cocinando-ando-94999',
    storageBucket: 'cocinando-ando-94999.firebasestorage.app',
    iosBundleId: 'com.example.cocinandoAndo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEa3WWOLyYASlIRswHKH1h8Ipw86LqBK0',
    appId: '1:39180378564:ios:e958eac259dbac4314c491',
    messagingSenderId: '39180378564',
    projectId: 'cocinando-ando-94999',
    storageBucket: 'cocinando-ando-94999.firebasestorage.app',
    iosBundleId: 'com.example.cocinandoAndo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwQrvbPwUqffI7Y5k473OkNuSehur-uFc',
    appId: '1:39180378564:web:6e4d675d1865344014c491',
    messagingSenderId: '39180378564',
    projectId: 'cocinando-ando-94999',
    authDomain: 'cocinando-ando-94999.firebaseapp.com',
    storageBucket: 'cocinando-ando-94999.firebasestorage.app',
    measurementId: 'G-SQYH2V7H59',
  );
}
